version: '3.8'

services:
    db:
        image: mysql:8
        container_name: db_taskify
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: dbTaskify
        ports:
            - '3308:3306'
        volumes:
            - db_data:/var/lib/mysql

    api:
        build: .
        container_name: api_taskify
        restart: always
        depends_on:
            - db
        ports:
            - '3000:3000'
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASS: 12345678
            DB_NAME: dbTaskify
        volumes:
            - .:/app
        command: npm run dev

volumes:
    db_data:
